server:
  port: 7999
  servlet:
    context-path: /convert
spring:
  application:
    name: convert
oss:
  domain: r0yg7lr7e.hn-bkt.clouddn.com
  bucket: fant
  accessKey:
  secretKey:
  expire: 3600